### DISCUSSION TITLE
ZabbixCI in GitLab CI example pipeline

### DISCUSSION THREAD

**Discussion by mcbrineellis** [retigra/ZabbixCI#149] [Show and tell]
I wanted to share a simple GitLab CI pipeline example with multiple Zabbix servers, you can use this as a starting point.

There is a CI variable $ZABBIX_PASSWORD, and the rest of the config I added to a `config-ci.yaml` file in the repo.

**.gitlab-ci.yml**

```
image:
  name: ghcr.io/retigra/zabbixci:0.3.5
  entrypoint: [""]

default:
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - cache

stages:
  - validate
  - deploy

.zabbix: &zabbix
  - ZABBIX_SITE: "SITE01"
    ZABBIX_URL: "https://zabbix.site01.company.net"
  - ZABBIX_SITE: "SITE02"
    ZABBIX_URL: "https://zabbix.site02.company.net
  - ZABBIX_SITE: "SITE03"
    ZABBIX_URL: "https://zabbix.site03.company.net"

validate:
  stage: validate
  tags:
    - docker
  parallel:
    matrix: *zabbix
  script:
    - zabbixci version -c config-ci.yaml 
      --zabbix-password "$ZABBIX_PASSWORD" 
      --zabbix-url "$ZABBIX_URL"
    - zabbixci pull -c config-ci.yaml --dry-run 
      --zabbix-password "$ZABBIX_PASSWORD" 
      --zabbix-url "$ZABBIX_URL" 
      --cache-path "./cache/$ZABBIX_SITE" 
      --pull-branch "$CI_COMMIT_BRANCH" 
      --git-password "$CI_JOB_TOKEN"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  allow_failure: true

deploy:
  stage: deploy
  needs: []
  tags:
    - docker
  parallel:
    matrix: *zabbix
  script:
    - zabbixci version -c config-ci.yaml 
      --zabbix-password "$ZABBIX_PASSWORD" 
      --zabbix-url "$ZABBIX_URL"
    - zabbixci pull -c config-ci.yaml 
      --zabbix-password "$ZABBIX_PASSWORD" 
      --zabbix-url "$ZABBIX_URL" 
      --cache-path "./cache/$ZABBIX_SITE" 
      --pull-branch "$CI_COMMIT_BRANCH" 
      --git-password "$CI_JOB_TOKEN"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  when: manual
```

**config-ci.yaml**

```
vendor: Company
set_version: true
zabbix_user: svc-zabbix
remote: "https://gitlab.company.net/zabbix/zabbix-templates.git"
git_username: "gitlab-ci-token"
verbose: true
```
